### PR TITLE
Merge from upstream bird v1.6.3

### PR DESCRIPTION
**Pull request by insequent**
As a preface, this PR's primary goal is to bring in BGP multipath into Calico. This may not be the best method, but seemed like the path of least resistance (we were advised not to run GoBGP is production just yet). v1.6.0 features have been out for a while now, so one can hope v1.6.3 has the bugfixes needed to keep this code base stable.

I should also note that for such a merge to work, some calico-node changes will be needed as well, but I wanted to get this PR up ASAP because of the review needed for the code discussed below.

This PR makes some huge assumptions on code I'm frankly not that familiar with. In particular, there were the following merge conflicts:

```
        both added:      .gitignore
        both modified:   sysdep/linux/netlink.Y
        both modified:   sysdep/linux/netlink.c  <-- Most conflicts here
        both modified:   sysdep/unix/krt.c
        both modified:   sysdep/unix/krt.h
```

The conflicts seemed to mostly be around `KRT_TUNNEL` and the ipinip work that was done with that. `sysdep/linux/netlink.c` in particular will need some scrutiny by someone whose worked on this before, and not just myself.

I'm open to discussion on any of this, so please let me know! Thanks all in advance for any time you can give.

### CODE REVIEW

**Comment by insequent** [comment]
And I have no idea how to work around CLA issues from preserved commits. Hard push from a maintainer if at some point we all agree on this PR?

**Comment by insequent** [comment]
This PR's diff is rough to read, and I'm liking this view better:

https://github.com/projectcalico/bird/compare/017da76b729cc36c4a3416995b06386235660f42...938df6d7c7b354d8ebc601604ce3c5e95c58e2ec

It's a diff between upstream bird v1.6.3 and my merge commit (i.e. everything Calico has stacked on top). It'll at least give you an idea of what choices I made for those merge conflicts.

**Comment by neiljerram** [comment]
Hi @insequent - Just to let you know that I'm planning time to look at this tomorrow.

**Comment by nelljerram** [comment]
@insequent I think this is looking fine.  Just running it through some tests, and if they look good (and if I can get past the CLA thing somehow) I will merge tomorrow.

**Comment by insequent** [comment]
Awesome, thanks @neiljerram

**Comment by nelljerram** [comment]
@insequent Sorry for leaving you here without a further update.  Our testing showed a problem with Calico operation on GCE, so I have been looking into that.  You can read the detail of that at #31.

So then I redid the merge and conflict resolutions myself.  The result of that is in a new PR at #33, and if you compare that against this PR, you can see where our resolutions differed.  In summary:

- in where and how the KRT_TUNNEL attribute is defined (not sure there is actually any observable change here, but I was looking earlier this year at upstreaming our changes, and that led me to the arrangement in #33, which I think is more 'right' w.r.t. the upstream code)

- the two neigh_find2 calls, as discussed in #31 

- the non-KRT_TUNNEL branch of the RTD_ROUTER case in nl_send_route - where the key thing is that the code here should be the same as upstream

- .gitignore changes, which I believe are unimportant 
 
If it's OK with you, I think the sensible thing now would be to close this PR and work on testing #33 instead.  Is that OK?

**Comment by insequent** [comment]
@neiljerram +1! As I noted above, I only vaguely knew what I was doing and making big assumptions. It'd take me quite a bit to fully consume the code and know what's going on. I'm relieved to have someone who knows what's going on to take the lead on this.

**Comment by nelljerram** [comment]
Thanks @insequent !

**Pull request closed without merging**
