### PR TITLE
Rebase on latest bird master 4c0b741ba7419e2cb816e1dc9a23096234d998e2

### PR DESCRIPTION
**Pull request by trois-six**
## Description
Hi,

The goal of this PR is to rebase the bird calico fork on the latest bird sources. I didn't choose to apply commit by commit because some commits failed to merge.
I applied the diff from https://github.com/BIRD/bird/commit/017da76b729cc36c4a3416995b06386235660f42 to https://github.com/BIRD/bird/commit/4c0b741ba7419e2cb816e1dc9a23096234d998e2 to https://github.com/projectcalico/bird/commit/abdb4353a7b4b1b98b61b3f31d8a4109387c0f83  and corrected the rejects by hand.

It's compiling and running nicely on my environment.

### CODE REVIEW

**Comment by caseydavenport** [comment]
@Trois-Six thanks for the PR. It would be great to pull in any upstream fixes.

A couple of things:
- Looks like the build is failing on Semaphore for this PR.
- I _think_ we'll want to maintain the original commits if we want to merge our fork back upstream one day. 

CC @neiljerram

**Comment by nelljerram** [comment]
@Trois-Six Thanks for looking at this!  As @caseydavenport says, I would certainly like to record this in Git(Hub) as a merge rather than as a rebase.  We last did that in March 2017, merging upstream v1.6.3, and it would be great if possible to do this time round similarly.

**Comment by trois-six** [comment]
Hi,
It's compiling on Semaphore now.

**Comment by nelljerram** [comment]
@Trois-Six I've just been looking at this a bit more, by starting off a merge (with v2.0.2) myself, with the intention of then comparing against your result.  Although there are only a handful of conflicts to look at, I am very conscious of some of the very subtle bugs that we've introduced in the past when doing this kind of thing (e.g. see https://github.com/projectcalico/bird/issues/31), so I really want to take care to do this right.

Having spent a little time on that now, and bearing in mind that - as far as I know - there is no immediate *need* for us to rebase on the v2 code, I think that it would be better for us to spend our time on properly upstreaming our BIRD patches.  That way, we won't have to do this kind of rebasing/merging again, and whether we're upstreaming or rebasing/merging, we need to fully understand our logical patches and work out how they are expressed in the latest BIRD code.

What do you think?  Would you be interested in helping to upstream these changes?

**Comment by nelljerram** [comment]
BTW, for other advocacy for upstreaming, please see #56

**Comment by trois-six** [comment]
I completely agree with you. I do not have enough time right now to upstream the changes, and I don't have the complete history of the project in mind. We are deploying a rather big cluster and our policy is to package as "systemd service"/"debian package" every infrastructure component of our k8s cluster. We think that infrastructure components should not run inside the cluster (pods). Doing so, I was rather disappointed by the fact that the Calico Project doesn't upstream its changes and I looked at the diff between bird master and the calico's fork.

**Comment by nelljerram** [comment]
Closing this because we've since merged up to v1.6.8, and the longer term plan is for us to rework so as no longer to need our own fork at all.

**Pull request closed without merging**
