### PR TITLE
Merge upstream BIRD v1.6.3 code

### PR DESCRIPTION
**Pull request by nelljerram**

### CODE REVIEW

**Comment by insequent** [comment]
Excellent! Thanks @neiljerram

**Comment by nelljerram** [comment]
@insequent If you don't mind me asking, have you been able to test yet whether this new BIRD code works for you in all the scenarios of interest to you?

(Just being curious / paranoid - I'm not asking because there is anything that we are aware of being wrong with it!)

**Comment by insequent** [comment]
@neiljerram Not yet, but I'll update when we do. We've been busy with other non-BGP projects for a while now.

**Comment by nelljerram** [comment]
@insequent Thanks, I'd appreciate that, for the extra level of confidence.

**Pull request merged**
