### PR TITLE
optimization debian package manager tweaks

### PR DESCRIPTION
**Pull request by rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

## Description
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport

### CODE REVIEW

**Comment by rajpratik71** [comment]
@tomdee @marenamat  requesting review.

**Comment by caseydavenport** [comment]
Seems fine to me so long as the build continues to work.

@Rajpratik71 looks like you have a conflict and will need to rebase, though.

**Comment by rajpratik71** [comment]
> Seems fine to me so long as the build continues to work.
> 
> @Rajpratik71 looks like you have a conflict and will need to rebase, though.

resolved the conflict . let wait for the ci test.

**Comment by rajpratik71** [comment]
@caseydavenport Please review . rebased to Upstream.

**Pull request merged**
