### PR TITLE
Add 32 bits arm(hf) build

### PR DESCRIPTION
**Pull request by aalaesar**
## Description
Add ability to compile or cross-compile for 32 bits arm architecture
- **type**: new feature
- **why this PR should be merged**: this is one of the components required to build the calico project for the arm architecture
- **testing** :  manually built the binary and used it to get the final calico arm image. The final image worked properly on a new kubernetes cluster composed of raspberry pi 3 & 2
- components affected: bird

## Notes:

Compared to #80, canonical name if different as I haven't found consensus on the arm's name.

## Todos
- [ ] Unit tests (full coverage)
- [x] Integration tests: Done
- [ ] Documentation
- [x] Backport

### CODE REVIEW

**Comment by aalaesar** [comment]
CI doesn't seems to work anymore.
Do I need to update a file  ?

**Comment by lwr20** [comment]
It seems that someone disabled the semaphore v1 build, and this repo doesn't have a semaphore v2 config yet.  

I've given myself a task to add a semphore v2 config.

**Comment by aalaesar** [comment]
🤦  just realized I didn't pushed the changes to rename the ARCH name to armv7
😖

**Pull request merged**
