### PR TITLE
arm64 support

### PR DESCRIPTION
**Pull request by deitch**
## Description
Provide compilation support for arm64 for `bird`, `bird64` and `birdcl`.

Changes are primarily around the build scripts and environment, not any actually C code (which compiles and runs as is on `arm64`, much to my surprise).

* new `Dockerfile` for `arm64`
* move default `Dockerfile` to `Dockerfile-amd64` and link `Dockerfile` to `Dockerfile-amd64` to keep default but have `amd64` be explicit
* Support new arch in `build.sh`
* Auto-detect `ARCH` in `build.sh`, but enable override via setting envvar
* New var `BUILDARCH` because arm64 is commonly referred to as `arm64` (including in docker/OCI multi-arch manifests), but gcc insists it is `aarch64`
* Update `create_binaries.sh` to exit out on first error - failed builds at earlier stages were causing it to keep going in unpredictable state
* Update `config.sub` and `config.guess` to latest versions from `gcc`, to support `aarch64`. The versions in place were 8+ years old.

Testing: I tested manually on `x86_64` (local docker) and `arm64` (courtesy of packet.net). I would be happy to run through Calico's automated CI if someone can point me to it.

This is the first step in getting calico `arm64`-friendly. Once this is in, I will start to look at getting the other components `arm64`-friendly and multi-arch images.

Reference https://github.com/projectcalico/calicoctl/issues/1475 and https://github.com/projectcalico/cni-plugin/issues/364

### CODE REVIEW

**Comment by caseydavenport** [comment]
@deitch awesome, thanks for the PR!

The Calico team is stretched pretty thin over the holdays but we'll pick this up in January.

**Comment by deitch** [comment]
> awesome, thanks for the PR!

Quite welcome. This won't be the first.

> we'll pick this up in January

Sure. I discussed this briefly by email with @liljenstolpe as well.

Two questions:

1. Can we agree that in principle an arm64-enabling PR _will_ go in (accepting that any individual PR may need changes, of course) in a timely fashion? If so, happy to start opening them for the other components of calico.
2. Do we have a standard automated CI for calico? Would like to get the tests in and working.

**Comment by caseydavenport** [comment]
> Can we agree that in principle an arm64-enabling PR will go in (accepting that any individual PR may need changes, of course) in a timely fashion? If so, happy to start opening them for the other components of calico.

Yep, we're very keen to get this in in the new year. Some components already have some work done on this, I think.

> Do we have a standard automated CI for calico? Would like to get the tests in and working.

We run FV / UT jobs on Semaphore on a per-repository basis. I haven't looked into arm64 support on semaphore, but in order to get the CI running as part of the standard check-in process will likely require work on our end. However, if you just want to start by running them locally there's a make target in each repo which will run the tests.

We also have post-submit e2e jobs which aren't in the public, so we'll need to do some thinking as to how we do that. I don't think we should block on that though - we can get the build and release infrastructure done while we sort that out.

**Comment by deitch** [comment]
> Yep, we're very keen to get this in in the new year. 

Sounds good to me.

> We run FV / UT jobs on Semaphore on a per-repository basis. 

Is it open to see? How would I trigger it?

> I haven't looked into arm64 support on semaphore

I did a quick check, could not find anything. Is Tigera a big enough customer of Semaphore to drive them to look at arm? I would be happy to connect them with Packet (with whom I do some work) to get them connect, if needed. @liljenstolpe has my email; feel free to drop me a line directly.

> there's a make target in each repo which will run the tests

Will do. Is there one for `bird` as well? Or just the other projects?

Looking forward to moving this forward.

**Comment by deitch** [comment]
As far as I can tell, all of the other projects depend upon [projectcalico/go-build](https://github.com/projectcalico/go-build), which _has_ merged in arm64 support, but the arm64 image wasn't push out to the docker hub.

I opened an issue there asking if want to push out the arm64 image, or (even better) use the `manifest-tool` to have a single multi-arch `calico/go-build` image. Once that clears, and this one as well, we can start working on felix, etc.

**Comment by deitch** [comment]
@caseydavenport digging my way into the other repos. Everything else seems to depend on go-build, which *is* multiple architecture, if not quite pushed out. See [this PR](https://github.com/projectcalico/go-build/pull/23) as well.

**Comment by djlwilder** [comment]
LGTM:  I tested these changes on ppc64le and saw no issues.

**Comment by caseydavenport** [comment]
> Will do. Is there one for bird as well? Or just the other projects?

I believe the testing for this is all in the other repos, so we'll have to merge and monitor other tests as it propagates through. 

> Is it open to see? How would I trigger it?

It will run against any PRs that are opened. I think once this guy is merged, we'll need to tag a new bird release with the new binaries and update the `calico/node` build to pull that in.

https://github.com/projectcalico/calico/tree/master/calico_node will need to be updated to produce arm64 images, using the binaries from here.

**Comment by caseydavenport** [comment]
The build / release process for this repo actually appears to be performed on CircleCI right now. In order to generate those binaries it seems we'll need a machine to build the arm64 and other arch variants.

**Comment by deitch** [comment]
We can get an arm64 to build from Packet. I have access to one to do a few one-off builds, but at some point it will need either to be leased from packet or integrated via CircleCI or some similar CI.

Any desire to look at QEMU-based building like @liljenstolpe pointed out in the issue repo?

**Comment by caseydavenport** [comment]
I'm not opposed to pursuing either option, though my preference is for starting with something as simple as we can get.

I noticed that Flannel does some magic in its Dockerfile which I think is intended to allow cross-compilation of Docker images: https://github.com/coreos/flannel/blob/master/Dockerfile.arm#L7

I'll admit I haven't looked at it in detail, so don't know if it would make sense for Calico, but I wonder if such an approach might help us at least get something out sooner rather than later.

**Comment by deitch** [comment]
I think flannel is just building all architectures on x86_64 by using golang's cross-compilation abilities.  It is interesting that they say that `qemu` is required for that, and even order that they actually _package_ it up into the container image, when it only is needed for building. 

That would work for everything in Calico except for this repo (`bird`) which is built in C. We could cross-compile as well using `gcc` (although I have never actually cross-compiled with `gcc` from `x86_64` to `arm64`). 

Where does that leave us?

1. Building: everything except `bird`, golang cross-compile is a real option. For `bird`, we could try `gcc` cross-compile and see. 
2. Testing: There aren't really tests here per se.

Is the `circle.yml` indicative that we use CircleCI for CI? It appears to run `build.sh`, which creates the binaries (and we could build a wrapper around it that will build for all known platforms with ease, providing multiple files in `./dist/`), but how does that get consumed?

Let's at least get bird out of the way? I would like to see the effort start to pay off. :-)

**Comment by caseydavenport** [comment]
> Is the circle.yml indicative that we use CircleCI for CI? It appears to run build.sh, which creates the binaries (and we could build a wrapper around it that will build for all known platforms with ease, providing multiple files in ./dist/), but how does that get consumed?

Yeah, CircleCI is used for this repo to get a build machine. So, the binaries produced in CircleCI will be consumed as part of a release of this repo.

I think that means we could update `build.sh` to do a cross build which will get run on CircleCI, and then cut a release which includes the cross-compiled binaries.  That would unblock us for now.

@deitch @neiljerram WDYT?

> Let's at least get bird out of the way? I would like to see the effort start to pay off. :-)

Yes, I completely agree :)

**Comment by deitch** [comment]
> I think that means we could update build.sh to do a cross build which will get run on CircleCI, and then cut a release which includes the cross-compiled binaries. That would unblock us for now.

Definitely! I have an impossibly busy week, but it includes many hours on planes, some of which have WiFi, I will try to modify this PR to include cross-building if the WiFi works well. If not, later this week/early next.

**Comment by deitch** [comment]
In the meantime, will rebase

**Comment by deitch** [comment]
Ugh. We don't *really* have a directory named `doc` and a file named `Doc`, do we?

(macOS APFS by default is case-insensitive. I have no idea why they did it, and if I had known, I would not have enabled it, but there you go)

And so it thinks I have `Doc` deleted (because `doc` exists) and therefore will not let me rebase. Bloody hell. I have no idea what to do with this now.

**Comment by deitch** [comment]
Ok, rebased. That APFS case-insensitivity is inane.

**Comment by deitch** [comment]
Could use a little feedback here @caseydavenport. The way it works now is as follows:

1. You start the build via `./build.sh`
2. You tell `./build.sh` what arch it is building for either by passing it the `ARCH` env var; if unset, it auto-detects via `uname -m`
3. It builds an arch-specific container image
4. It builds the binary for that arch using the arch-specific image..

I am thinking of leaving the ones that are there the way they are, so default is just "build for my arch", the way it was. But, will add an `ARCH=all` option to `build.sh` (extends 2 above), which will build a cross-build image (3 above), which then will store all of the built binaries as `dist/bird-<arch>`. That leaves the existing process all working, and makes it really easy to "just build for my arch", but adds an option to cross-build.

Make sense?

**Comment by djlwilder** [comment]
The ARCH=all may be hard to implement for some of the other pieces of calico,  for example calico/node, has many make targets and each one would need to be run for every arch.

How would I do a native build?  Would it be up to the buildbird-arch to detect what arch its running on? Using the qemu-arch-user method it should just do the right thing (only use qemu when not building on the BUILDARCH)  but how will the cross compiler method work?   The container containing the cross compilers needs to match the arch its running on.  One buildbird containing all the cross compilers and a native container for each support arch?

**Comment by deitch** [comment]
> for example calico/node, has many make targets and each one would need to be run for every arch

Can you elaborate a bit?

> How would I do a native build? Would it be up to the buildbird-arch to detect what arch its running on? 

Yes. Running `ARCH=x86_64 ./build.sh` would build for `x86_64`, or even just `./build.sh` when on `x86_64` would detect that I am on `x86_64` and build for that platform. That part seems easy enough to work with.

> Using the qemu-arch-user method it should just do the right thing

True, if unfortunately terribly slow. Although we could speed it up by running qemu inside a container. It still won't be very fast, but at least all of the setup will be pre-done.

The fastest method is cross-compilation. For the golang repos (every one except this), it is much simpler.

> The container containing the cross compilers needs to match the arch its running on. 

Yes. The host platform is the current arch, the target platform is the target. We already have `Dockerfile`s for each host arch (even if amd64 and arm64 are identical, and the only difference for ppc64le is the `FROM`), so that isn't a big deal.

> One buildbird containing all the cross compilers and a native container for each support arch?

Yes. 

I think running it inside qemu might be easier, if slower, but gcc cross-compilation seems to me to be the more straightforward route. Do you disagree?

**Comment by djlwilder** [comment]
>>  for example calico/node, has many make targets and each one would need to be run for every arch
>Can you elaborate a bit?
Never mind I was think how we would do that in a makefile not in build.sh.

My question on native build was how would I build arm on arm or ppc on ppc?

**Comment by deitch** [comment]
> My question on native build was how would I build arm on arm or ppc on ppc?

That part is easy. If you just run `./build.sh` right now, it runs native, arm64 on arm64, x86_64 on x86_64, ppc on ppc. The challenge was having a single build run that provides all 3: arm64, ppc and x86_64 running on one of them.

**Comment by deitch** [comment]
So... cross-compilation is not as easy as it looks. I could not find any pre-built gcc `(host,target) = (x86_64,arm64)` or vice-versa, or ppc variants, ready to run for alpine. They do have ppc support, and arm64, and amd64, but only where `host == target`. 

That leaves two options:

1. Rebuild the toolchain ourselves, i.e. gcc with the correct `--host=` and `--target=` with all of the variants (pain).
2. Use qemu.

I almost can get the second done, if I could figure out how to run a build from a specific `alpine:3.6`. Now that it is multi-arch via manifests, it is difficult to specify a specific one, since the docker engine takes the one for the architecture on which it is running.

Once that is in place, it is possible to do `qemu-arm apk --update add alpine-sdk ....` etc. and then do the build.

**Comment by deitch** [comment]
Of course, if someone wants to rewrite `bird` in go, all of this goes away....

**Comment by deitch** [comment]
So.... any objection to switching from alpine to debian container image for the build of bird?

When running natively, it is fine. But getting it to run in qemu is a royal pain - especially when you don't have access to the kernel and can do binfmt magic, and in any case the CI providers seem to run old kernels - but debian has really nice and easy to use cross-compilation support. 

This is *not* true of Alpine, where pre-built cross-compilation doesn't exist. I don't think we should be compiling our own `gcc` binaries here.

If we do the build in debian, a lot of this is doable.

Thoughts?

**Comment by caseydavenport** [comment]
> Of course, if someone wants to rewrite bird in go, all of this goes away....

Calico does include a community supported GoBGP integration... It's not yet as well-tested or as stable as the integration with bird, so I don't think it obviates the need to solve this problem. 

> So.... any objection to switching from alpine to debian container image for the build of bird?

I'm going to defer to @tomdee for this one, but given the situation we're in it seems sensible to me.

**Comment by deitch** [comment]
> Calico does include a community supported GoBGP integration

I was looking at that. I think it would be a better long term solution - why support one forked project in C when everything else is in go and works multi threaded on multiple cores and ... - but I get that it takes time to get there.

> given the situation we're in it seems sensible to me

OK. Looks like I just about have it working for cross-compiling. Need to:

1. test two more binaries
2. one last tweak in `create_binaries.sh`
3. test in circleCI

Expect an updated PR here soon.

**Comment by deitch** [comment]
OK, fully updated. I also expanded the README.md to explain how build works.

Let me know @caseydavenport . I like this one. :-)

**Review by tomdee — APPROVED** [review]

**Comment by djlwilder** [comment]
I suggest adding  "--rm"  to the docker run command in build.sh and remove the "docker rm" at the bottom.  If the build fails the "docker rm" is not run and the container must be removed by hand before running again.

Also:
circle.yaml was updated but it looks as if semaphore is not using it,  it is still running ./build.sh .

I plan to insert the cross built binaries into my ppc64le test environment.

**Comment by deitch** [comment]
> I suggest adding "--rm" to the docker run command in build.sh and remove the "docker rm" at the bottom

Every time I edited, I did that then removed it. I figured if someone did it in two steps, there _had_ to be a reason, so don't mess with it. But I think your argument carries more weight (and I should have followed my instinct). I will do it, and someone can ask me to undo if needed.

> I plan to insert the cross built binaries into my ppc64le test environment

Thanks, let us know?

**Comment by deitch** [comment]
> circle.yaml was updated but it looks as if semaphore is not using it, it is still running ./build.sh

semaphore apparently is not configured via a file in the repo like Jenkins/Circle/Travis, but instead via the UI. Someone with authorization needs to go into sempahoreci.com and change `.build.sh` to `ARCH=all ./build.sh`

**Comment by caseydavenport** [comment]
> semaphore apparently is not configured via a file in the repo like Jenkins/Circle/Travis, but instead via the UI. Someone with authorization needs to go into sempahoreci.com and change .build.sh to ARCH=all ./build.sh

I can do this once merged

**Comment by deitch** [comment]
I missed the merge notification, @caseydavenport . Thank you!

On now to the go-build PR and then the rest. Should I flag you there?

**Comment by deitch** [comment]
btw, I am curious. Why is the main branch `feature-ipinip` rather than `master`?

**Comment by caseydavenport** [comment]
@deitch thanks for the great effort on this one :)

Semaphore has been updated. 

Please do flag me on those PRs, but I suspect @tomdee should be the primary reviewer :)

**Comment by nelljerram** [comment]
@deitch It's because support for IP-in-IP routes is the only thing we've added to the upstream BIRD code.

**Comment by nelljerram** [comment]
FYI we began a conversation, a while back, about potentially upstreaming those changes - at https://www.mail-archive.com/bird-users@network.cz/msg01314.html - and the BIRD maintainer was open to that; but unfortunately we have not yet prioritized progressing that. If those were upstreamed, however, I believe we would need our own BIRD fork any more.

**Comment by deitch** [comment]
> It's because support for IP-in-IP routes is the only thing we've added to the upstream BIRD code.

Ah, got it. Thanks.

**Comment by deitch** [comment]
> Please do flag me on those PRs, but I suspect @tomdee should be the primary reviewer

Sure thing, will do.

**Pull request merged**
